### ISSUE TITLE
Weird right arm bone when exported to mixamo & binding to active armature not working (Blender 3.2.1)

### ISSUE THREAD

**Issue by prast77** [pKrime/Expy-Kit#23]
Hello, 

I have weird right arm top bone when exported to mixamo & binding to active armature not working in Blender 3.2.1
Try to use both ExpyKit_v05.zip & Expy-Kit-main_2.zip but still have some problem
Please Check attached file

Thank You

edit: binding seems to work, have to set the constrain setting to FK before set binding to active armature

[File.zip](https://github.com/pKrime/Expy-Kit/files/9332884/File.zip)

**Comment by pKrime** [comment]
Hi,

thank you very much for sending your files, apologies for the delay but I couldn't look at this until today. Looking at the _Armature_ in **blender rig.blend** it would seem that the Rigify rig has Mixamo names

![immagine](https://user-images.githubusercontent.com/5176115/184655983-dfd969b8-6653-43ea-9db9-24a2fbde9bc5.png)

this is confirmed if you select, say the control for the shoulder, and it is **LeftShoulder** instead of **shoulder.L**

On the other hand, the skeleton contained in **Export from blender.fbx** kept the Rigify names (e.g. **DEF-shoulder.L**).

I think this is what happened:

you have followed all the steps correctly, but when it was time to convert the bone names to **Mixamo**, **Source Preset** was set to **Rigify Controls** rather then  **Rigify Deform**. The character uploaded to _Mixamo_ had _Rigify_ names.

Surprisingly, that almost worked: Mixamo kind of grasped the Rigify character. Looking closer, you can see how Mixamo mistook the arm mid bone for the elbow

![immagine](https://user-images.githubusercontent.com/5176115/184657022-042847f0-e1d4-4b7f-a416-f7ce4619eef5.png)

Here's what I did to bring everything back to work:

- First: Renamed the character controls so that they follow Rigify again. _Right Click_ in pose mode, **Conversion**->**Convert Bone Names**. **Source Preset = Mixamo**, **Target Preset = Rigify Controls**. Saved the file as **blender rig.fix**
- Time to export our .fbx: **Conversion->Rigify Game Friendly** to fix the hierarchy, then **Conversion->Convert Bone Names**, **Source Preset = Rigify Deform**, **Target Preset = Mixamo**.
- Select Armature and Mesh, export .fbx, enable **Selected Only** in the general options, enable **Deform Bones Only** and disable **Add Leaf Bones** in the Armature options
- Upload to Mixamo, get animations
- Import .fbx in blender, and bind: select Control Armature, select animated skeleton, **Binding->Bind to Active Armature**, **Bind Target = Mixamo**.

I have attached a .zip containing the "fixed" files: now that the rigs are back to known presets I can also bind to T-Pose , Without Skin, animations, and use IK controls with **Chain Look At**.

Please let me know if you need more help, and thanks again for the files: helped a lot with addressing the issue

Cheers
p.

[Report.zip](https://github.com/pKrime/Expy-Kit/files/9337823/Report.zip)

**Comment by prast77** [comment]
Hi,

Thank you so much, this helps a lot, now everything is working very well,
thank you very much

Pada tanggal Sen, 15 Agu 2022 pukul 21.58 pKrime ***@***.***>
menulis:
