### ISSUE TITLE
can't extract meta-rig 

### ISSUE THREAD

**Issue by ani111222** [pKrime/Expy-Kit#30]
the meta rig button don't work, any tip?
![image](https://user-images.githubusercontent.com/127549094/224414826-a451921d-5096-4a1d-ac3b-94a9c20cab0e.png)

**Comment by ani111222** [comment]
yeah its enabled

**Comment by ani111222** [comment]
I asked my friends they said it's something to do with the version, i tried to instal blender 3.0 another versions of the addon
I even tried using different armatures but still nothing

**Comment by ani111222** [comment]
do you think it has something to do with the version of blender?

**Comment by pKrime** [comment]
Hi, which version are you using? It shouldn't matter but I will try to reproduce the error.

the ExtractMetarig operator checks those conditions

- there should be an active object
- the active object should be an armature
- blender is in pose mode
- rigify should be enabled

The first three should be satisfied already, perhaps I do something wrong when checking for rigify.

Can you please send me a .blend file of yours, so that I can check the scene?

Thanks!

**Comment by ani111222** [comment]
sure
im gonna send the two that i am using, with controll rig and just the bones

**Comment by ani111222** [comment]
and im using 3.4.1, yes there is a active object, there is an armature, and it is in pose mode.

**Comment by ani111222** [comment]
do your addon have a problem with mixamo controll rig? or vroid models?

**Comment by ani111222** [comment]
https://www.mediafire.com/file/cao5w1u5eh8fwqk/with_controll_rig.blend/file with control rig

**Comment by ani111222** [comment]
https://www.mediafire.com/file/cao5w1u5eh8fwqk/with_controll_rig.blend/file with control rig

**Comment by ani111222** [comment]
if you want i can give you my discord. so we cant talk better.

**Comment by pKrime** [comment]
Sure, please let me know how I can join. I tried to extract a metarig of your character, and although something is off, I can launch the operator, so it's not the scene.

**Comment by ani111222** [comment]
my discord is AN1#9433

**Comment by ani111222** [comment]
maybe compatibility issues with other addons?

**Comment by pKrime** [comment]
Closing the issue as re-enabling rigify fixed it
