### ISSUE TITLE
AttributeError: 'EditBone' has no attribute 'layers'

### ISSUE THREAD

**Issue by Mohammad9760** [pKrime/Expy-Kit#46]
I followed these steps:
> upload my character to Mixamo and rig it
> download the character with Original pose
> imported it in Blender
> Extract Meta-Rig 
> generate Rigify rig from the metarig
> downloaded a walk animation from Mixamo and imported in Blender
> select the Rigify then select the walk animation rig and go to pose mode
> Bind to active armature with 'To Bind' set to Rigify_Controls and 'Bind Target' to Mixamo

https://github.com/pKrime/Expy-Kit/assets/79392031/f9052810-28b3-4a05-9f51-38c4d22372d0

I expected it to add constraints to the Rigify rig. am I missing something?
please help!
thanks

**Comment by Mohammad9760** [comment]
OK, I tried this in Blender 4.0.1 and there are no bone layers, there is bone collections.
is this what's causing the issue?
also the imported animation has no bone collection but I assume that is not what's causing the problem since the python traceback goes back to an AttributeError not some kind of Null reference, but I don't know better to know what's going on.

**Comment by Mohammad9760** [comment]
is there a recommended Blender version that works with this add-on?

**Comment by mechanic-kharkiv** [comment]
It seems to be fixed since [fa4de7cd](https://github.com/pKrime/Expy-Kit/commit/fa4de7cd337882c66e6bc1529f5202d15dba2f19). So, try to download the latest version, and try again.

**Comment by Mohammad9760** [comment]
> It seems to be fixed since [fa4de7cd](https://github.com/pKrime/Expy-Kit/commit/fa4de7cd337882c66e6bc1529f5202d15dba2f19)

is there a release for that?

**Comment by mechanic-kharkiv** [comment]
> is there a release for that?

It depends on whether you have pressed that green button "Code > Download zip" or not. ;-) If yes, then the 'release' must be in your download directory, just install it in blender as any other add-on (ensure to uninstall previous version first).
The power of git is the ability to restore a source tree at any point in history. A release is just another point in history. As for your `v0.5.2` (detected by the line number in your video) - the very old point (there are many nice improvements since then).
If you like to fiddle with various blender versions (as I do), then you may give a try to my fork (#44 ) where I'm trying to have it working in a lot of versions, starting from 2.76 (but be aware, it's not too stable yet, just WIP).

**Comment by Mohammad9760** [comment]
oh, thanks.
I didn't realize I could just install the repo.

**Comment by mechanic-kharkiv** [comment]
Huh, gangsta.  :-)  (as stated [right here](https://github.com/pKrime/Expy-Kit#how-to-use)) :-))

**Comment by Mohammad9760** [comment]
yeah, whatever. I'm guilty of being lazy when it comes to reading docs

**Comment by Hepworks** [comment]
Hey thanks!!!
