### ISSUE TITLE
Feature request: Retarget from rigify controls to rigify controls

### ISSUE THREAD

**Issue by sschoellhammer** [pKrime/Expy-Kit#56]
Hello there,

it would be great to be able to retarget controls animation between rigify characters - maybe this is already possible but I couldn't find an option.. Even better if the result would not bake but only create transform keys where the source has them :o

**Comment by pKrime** [comment]
Hi, unless I am mistaking the first request, that should be possible by using the "Rigify Controls" preset for both characters: I have tested that and it seems to work.

I have a non-baking solution in the making, not sure if it's safe for production though.

Please re-open the issue in case Rigify2Rigify turns out to be problematic

**Comment by sschoellhammer** [comment]
You are right, it is working and I should rtfm :P 
Being able to set keys on the constrained controls would be super nice :)
Imagine the use case where you have a set of animation done inhouse and you want to transfer that to another body type and be able to continue doing adjustments to match the personality
